language: python
python: 2.7
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=py2.7
    - TOXENV=pypy
    - TOXENV=cov
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls